{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "319ae3c4_d06e7bd8",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 5
      },
      "lineNbr": 0,
      "author": {
        "id": 5634
      },
      "writtenOn": "2021-04-19T18:37:02Z",
      "side": 1,
      "message": "Turned out there are 2 more instances of List() being called from the network thread. This patch set attempts to call them out by renaming them to UnsafeList().\n\nWill delete them in a later CL.\n",
      "revId": "3045d412fbe8ddda9f7c98177c1544919b8313bd",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}