{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "6bfcab1e_cf5e6481",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 15909
      },
      "writtenOn": "2021-01-18T00:12:41Z",
      "side": 1,
      "message": "Thank you for working on this.",
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "5cb1bd6c_4fef98e3",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 5087
      },
      "writtenOn": "2021-01-15T14:48:09Z",
      "side": 1,
      "message": "Here it looks like Chromium is using the go client instead of the python one. This is probably a requirement for CAS if I remember correctly. Is the go client a drop in replacement?",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "82eef17a_1036dd13",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 5087
      },
      "writtenOn": "2021-01-15T14:56:19Z",
      "side": 1,
      "message": "I see https://chromium-review.googlesource.com/c/chromium/src/+/2576880. I wonder if this can be done in the same CL.",
      "parentUuid": "5cb1bd6c_4fef98e3",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d4879904_a4f73a58",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 5087
      },
      "writtenOn": "2021-01-15T17:09:16Z",
      "side": 1,
      "message": "I am working on it, just some tests failing... I will upload on Monday.",
      "parentUuid": "82eef17a_1036dd13",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "46249d36_d2ca2108",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 15909
      },
      "writtenOn": "2021-01-18T00:12:41Z",
      "side": 1,
      "message": "Yes, you need to use the Go swarming, which has CAS support.\nLet me know if you have questions.",
      "parentUuid": "d4879904_a4f73a58",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "4d2b529f_9bd5084f",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 5087
      },
      "writtenOn": "2021-01-25T13:27:21Z",
      "side": 1,
      "message": "Thanks, sorry for the delay. I\u0027ve had a busy week but I am starting again to work on this.",
      "parentUuid": "46249d36_d2ca2108",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "41279a7a_ce2f5a2f",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 15909
      },
      "writtenOn": "2021-01-26T03:01:54Z",
      "side": 1,
      "message": "No worries. let me know if you need help.",
      "parentUuid": "4d2b529f_9bd5084f",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "313a80f3_510dafd4",
        "filename": "tools_webrtc/mb/mb.py",
        "patchSetId": 1
      },
      "lineNbr": 380,
      "author": {
        "id": 5087
      },
      "writtenOn": "2021-01-27T12:34:30Z",
      "side": 1,
      "message": "Ok, after syncing with the V8 team it looks like this is not used by WebRTC\u0027s recipes (see https://source.chromium.org/search?q\u003d%22self.m.chromium.mb%22\u0026sq\u003d\u0026ss\u003dchromium%2Finfra%2Finfra:parent%2Fbuild%2Frecipes%2Frecipe_modules%2Fwebrtc%2F for the MB usage from WebRTC\u0027s recipe_module).\n\nI wonder if we should just delete this code from WebRTC but this will break usage of:\n\n  $ tools_webrtc/mb/mb.py run ...\n\nThe tests fail with:\n\n./mb_unittest.py\nvpython ./mb_unittest.py (0.76s) failed\n.....................F.\n\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\u003d\nFAIL: test_run_swarmed (__main__.UnitTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"./mb_unittest.py\", line 769, in test_run_swarmed\n    \u0027base_unittests\u0027], mbw\u003dmbw, ret\u003d0)\n  File \"./mb_unittest.py\", line 185, in check\n    self.assertEqual(actual_ret, ret)\nAssertionError: 1 !\u003d 0\n\nI suspect our mb.py is quite outdated so some update of the code should fix.",
      "parentUuid": "41279a7a_ce2f5a2f",
      "range": {
        "startLine": 373,
        "startChar": 0,
        "endLine": 380,
        "endChar": 20
      },
      "revId": "478cbd5ffd6261cdee8d15b888e3295f16d4b35d",
      "serverId": "58829da1-049c-39fb-b951-ebdcd0984767"
    }
  ]
}